// export const disciplines = [
//     {
//         title:
//             "Disciplina 1 | Fundamentos da inovação na beira leito: o futuro do cuidado",
//         items: [
//             "Introdução a inovação na beira leito - 14: 33",
//             "O contexto atual e a saúde do futuro - 11:05",
//             "O desafio da enfermagem - 10: 45",
//             "Introdução ao Hyper Thinking - 09:07",
//             "Visão exponencial: como vemos o mundo - 10: 35",
//             "Aprendizagem acelerada: como aprendemos - 27: 59",
//             "Os seis chapéus do pensamento - 14: 59",
//             "Conexões evolutivas e poder de execução - 12: 54",
//             "Introdução a inovação na ACP - 11: 33",
//             "Perspectiva Ampliada do Cuidado - 09: 36",
//             "Relação interprofissional e ACP - 11: 28",
//             "Construção de vínculo - 13:00",
//             "Introdução as novas relações e modelos de trabalho - 13:00",
//             "Entrega virtual de saúde - 22:08",
//             "Implicações da entrega virtual na enfermagem - 13: 26",
//             "Transformação digital na enfermagem - 11: 14",
//             "Sustentabilidade, equidade e força de trabalho - 08: 50",
//             "Atividade obrigatória",
//             "Indicação de leitura",
//         ],
//     },
//     {
//         title:
//             "Disciplina 2 | Gestão de Recursos e Logística em Emergências Hospitalares",
//         items: [
//             "Introdução à gestão no cuidados - 10: 29",
//             "O processo de gerenciar conflitos - 06: 43",
//             "O antagonismo da enfermagem - 11: 20",
//             "Competências na gestão dos cuidados - 14: 54",
//             "Competências da enfermeira gestora - 16: 12",
//             "Introdução: Códigos e fluxos - 38: 49",
//             "Alinhamento multiprofissional - 22: 11",
//             "Safety Huddle - 12:05",
//             "Cuidados proporcionais e metas - 17: 42",
//             "Introdução à segurança do paciente e gestão da qualidade - 08: 55",
//             "As dimensões da gestão de cuidados - 22: 24",
//             "Discussão sobre caso real - 08: 58",
//             "Trilogia de Juran, ferramentas proativas e cultura de qualidade - 11: 24",
//             "Segurança psicológica e cultura de segurança - 08: 52",
//             "Apresentação do caso 1 - 10: 42",
//             "Apresentação e discussão caso 2 - 18: 55",
//             "Apresentação e discussão do caso 3 - 18: 52",
//             "Fórum de discussão",
//         ],
//     },
//     {
//         title:
//             "Disciplina 3 | Prática avançada da enfermagem e rotinas assistenciais diante do paciente que intercorre",
//         items: [
//             "Introdução a EPA - 17:40",
//             "Quem é o profissional da EPA - 18:46",
//             "Perfis de atuação e implicações - 18:34",
//             "Aprofundando noções sobre PAE - 10:56",
//             "Entendendo intercorrências - 08:40",
//             "Base clínica da PAE - 29:11",
//             "Vigilância clínica do paciente - 24:58",
//             "Introdução ao raciocínio clínico - 12:23",
//             "Teoria do processamento dual - 16:00",
//             "Etapas do raciocínio e o julgamento clínico - 08:57",
//             "Desenvolvimento e aprimoramento do raciocínio clínico - 07:48",
//             "Conceitos para construção do mapa mental - Parte 1",
//             "1. Caso clínico 1 (etapa 1) - 28:01",
//             "2. Caso clínico 1 (etapa 2) - 31:24",
//             "3. Caso clínico 2 - 22:21",
//         ],
//     },
//     {
//         title: "Disciplina 4 | Liderança e Gestão de Equipe",
//         items: [
//             "Contexto inicial da liderança criativa - 19:15",
//             "Perfil do líder criativo - 28:46",
//             "Introdução ao encantamento do cliente interno - 35:42",
//             "Liderança inspiradora - 26:18",
//             "Lidando conflitos a partir da liderança inspiradora - 20:28",
//             "Influência da liderança na cultura organizacional - 06:48",
//             "Dimensões do líder inspirador - 21:24",
//             "Ferramenta de gestão eficiente de recursos humanos - 26:18",
//             "Introdução ao mindset de inovação na liderança - 25:14",
//             "Autoconsciência como ferramenta do mindset de inovação - 12:23",
//             "Composição de um profissional completo - 27:47",
//             "Confiança como ferramenta do mindset de inovação - 17:30",
//             "Empatia como ferramenta do mindset de inovação - 17:19",
//             "Entendendo sobre soft skills - 16:49",
//             "Como resolver problemas? - 15:51",
//             "Gestão de pessoas - 18:24",
//             "Review dos conceitos - 30:37",
//             "Situação global dos ambientes de mercado - 27:41",
//             "Influência do carisma e o autoconhecimento - 26:14",
//             "Relevância do autodomínio - 15:06",
//             "Conceituando conflitos e entendendo sua relevância - 17:20",
//             "Discussão sobre experiências conflituosas - 28:22",
//             "Caminho do conflito e estratégias para evitá-lo - 33:19",
//             "Negociação e comunicação não-violenta para a resolução do conflito - 15:14",
//             "Introdução ao contexto dos desafios da enfermagem - 23:06",
//             "Primeiros passos para mudar o seu contexto - 18:00",
//             "Etapas da resolução de conflitos - 08:53",
//             "Atividade prática: Solucionando problemas a partir de processos - 24:56",
//             "As habilidades esperadas de um enfermeiro padrão - 19:23",
//             "Como desenvolver habilidades de liderança - 10:05",
//             "Dimensionamento de enfermagem e escala de plantão - 10:04",
//             "Fórum de discussão",
//             "Atividade: Construindo seu perfil MBTI",
//         ],
//     },
//     {
//         title: "Disciplina 5 | Tomada de decisão",
//         items: [
//             "PPP: Princípio, preferências e pensamento crítico - 24:03",
//             "Avaliação primária - 29:43",
//             "Noções iniciais e interpretação de ECG - 23:42",
//             "Introdução a Ultrassom Point Of Care - 15:01",
//             "Ultrassom como ferramenta de cuidado - 26:14",
//             "Compreendendo o USG - 14:30",
//             "Estratégias para começar a utilizar a Ultrassom - 07:06",
//             "Introdução a Gasometria - 13:30",
//             "Fundamentos da Gasometria - 14:59",
//             "Análise bioquímica - 19:29",
//             "Fundamentos do princípio ácido-base - 27:55",
//             "Simulação clínica - Caso 1 - 40:36",
//             "Debriefing - Caso 1 - 34:39",
//             "Simulação clínica - Caso 2 - 18:11",
//             "Debriefing - Caso 2 - 26:49",
//             "Simulação clínica - Caso 3 - 13:41",
//             "Debriefing - Caso 3 - 18:46",
//         ],
//     },
//     {
//         title: "Disciplina 6 | Urgências Cardiovasculares",
//         items: [
//             "Fundamentação | Função Cardiovascular",
//             "Síndrome Coronariana Aguda - 19:14",
//             "Sistema de cuidados centrados no paciente com SCA - 10:20",
//             "Tomada de decisão - 13:21",
//             "Interpretação de ECG - 19:30",
//             "Manejo inicial com Killip-Kimball e Escore Heart - 09:49",
//             "Farmacologia na SCA - 25:44",
//             "Atuação do enfermeiro no contexto da Insuficiência Cardíaca Aguda - 15:54",
//             "Avaliação de risco imediato a vida e cuidados na ICA - 20:18",
//             "Introdução à atuação do enfermeiro no contexto de arritmias - 13:00",
//             "Arritmias: Taquiarritmias",
//             "Arritmias: Bradiarritmia",
//             "Casos clínicos e identificação de arritmias - 28:40",
//             "Distúrbios de condução e casos clínicos - 11:04",
//             "Tratamentos químicos e elétricos para arritmias e bloqueios - 11:11",
//             "Caso clínico - Sala vermelha - 27:34",
//             "Debriefing do caso - 40:47",
//             "Caso clínico - Enfermaria - 20:20",
//             "Debriefing do caso - 41:19",
//         ],
//     },
//     {
//         title: "Disciplina 7 | Urgências Gastrointestinais, Renais e Metabólicas",
//         items: [],
//     },
//     {
//         title: "Disciplina 8 | Urgências maternas e cuidados com o recém nascido",
//         items: [],
//     },
//     {
//         title: "Disciplina 9 | Condições de Choque",
//         items: [],
//     },
//     {
//         title: "Disciplina 10 | Farmacologia Avançada",
//         items: [],
//     },
//     {
//         title: "Disciplina 11 | Rotinas Hospitalares",
//         items: [],
//     },
//     {
//         title: "Disciplina 12 | Enfermagem Baseada em Evidência",
//         items: [],
//     },
// ];


export const disciplines = [
    { title: 'Disciplina 1 | Fundamentos da Inovação e o Futuro do Cuidado' },
    { title: 'Disciplina 2 |  Gestão e Recursos e intercorrências hospitalares' },
    { title: 'Disciplina 3 | Prática Avançada da Enfermagem' },
    { title: 'Disciplina 4 | Liderança ' },
    { title: 'Disciplina 5 | Gestão de equipe' },
    { title: 'Disciplina 6 |  Tomada de decisão' },
    { title: 'Disciplina 7 |  Farmacologia Avançada' },
    { title: 'Disciplina 8 |  Urgências cardiovasculares' },
    { title: 'Disciplina 9 | Urgências gastrointestinais, renais e metabólicas' },
    { title: 'Disciplina 10 |  Urgências maternas e cuidados com o recém nascido' },
    { title: 'Disciplina 11 |  Condições de Choque' },
    { title: 'Disciplina 12 |  Rotinas Hospitalares e Megacod' },
]